FROM node:alpine

WORKDIR /app

# Copy only package files first
COPY ./frontend/package*.json ./

# Install dependencies inside the container
RUN npm install

# Copy the rest of the frontend code
COPY ./frontend/ /app/

EXPOSE 5173

CMD ["npm", "run", "dev"]