
services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
