# Generated by Django 5.1.7 on 2025-06-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock_quantity',
            new_name='stock',
        ),
    ]
