# Generated by Django 5.1.7 on 2025-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_stock_quantity_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
